// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trellura.API.Data;

namespace Trellura.Migrations
{
    [DbContext(typeof(TrelluraDbContext))]
    [Migration("20201005182927_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("Trellura.Models.Cartao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cartoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = 1,
                            Titulo = "Tarefa 1"
                        },
                        new
                        {
                            Id = 2,
                            Status = 1,
                            Titulo = "Segunda tarefa"
                        },
                        new
                        {
                            Id = 3,
                            Status = 1,
                            Titulo = "Tarefa 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
